<a href="https://colab.research.google.com/github/Gokulrajan16/python/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

List vs Numpy

In [4]:
from time import process_time

In [6]:
python_list=[i for i in range(20000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)

0.0036576149999998364


In [8]:
np_array=np.array([i for i in range(20000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print(end_time-start_time)

0.0017805580000000987


In [9]:
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [10]:
#creating a 1 dim array
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [11]:
a.shape

(5,)

In [14]:
b=np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(b)
b.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

In [16]:
c=np.array([(1,2,3,4,5),(6,7,8,9,10)],dtype=float)
print(c)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


Initial placeholders of numpy array


In [19]:
x=np.zeros((4,5),dtype=int)
print(x)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [23]:
#create an identity matrix
a=np.eye(5,dtype=int)
print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [26]:
#create a numpy array with random values
b=np.random.random((3,4))
print(b)


[[0.03517196 0.21507838 0.33931451 0.91860323]
 [0.30541145 0.94833047 0.51797299 0.24381628]
 [0.41208289 0.67101044 0.60957374 0.28525659]]


In [28]:
c=np.random.randint(10,100,(100,100))
print(c)

[[85 81 81 ... 29 16 56]
 [62 85 47 ... 11 74 15]
 [39 51 10 ... 15 14 56]
 ...
 [79 22 91 ... 62 75 55]
 [82 73 17 ... 60 59 94]
 [58 69 82 ... 35 47 44]]


In [30]:
#create a list to numpy array
list2=[5,6,7,8,20]
np_array=np.asarray(list2)
print(np_array)
type(np_array)

[ 5  6  7  8 20]


numpy.ndarray

Analysing a numpy array

In [35]:
e=np.random.randint(10,90,(6,6,6))
print(e)

[[[48 20 79 45 30 63]
  [73 14 51 26 55 86]
  [56 34 30 87 15 39]
  [47 29 77 81 46 49]
  [29 24 23 59 79 37]
  [55 84 75 70 78 54]]

 [[24 21 17 24 35 25]
  [39 31 78 38 83 87]
  [40 30 86 32 13 58]
  [70 81 44 42 47 80]
  [16 61 20 24 49 56]
  [62 42 15 19 77 59]]

 [[70 42 80 46 36 42]
  [54 46 75 45 46 40]
  [58 69 11 43 10 55]
  [72 40 89 26 44 34]
  [51 46 52 37 71 25]
  [56 88 35 12 32 21]]

 [[17 18 79 76 89 40]
  [32 10 70 38 24 67]
  [40 21 13 79 58 81]
  [24 71 88 54 57 70]
  [40 82 30 42 58 56]
  [74 79 69 37 81 83]]

 [[16 70 89 66 54 26]
  [86 14 59 49 58 43]
  [15 27 74 50 77 22]
  [25 10 48 46 11 74]
  [36 29 53 20 52 42]
  [76 12 70 10 28 76]]

 [[80 63 88 34 22 35]
  [39 67 47 20 55 10]
  [84 32 43 77 51 70]
  [35 60 60 12 67 38]
  [75 77 50 82 84 42]
  [18 17 45 78 77 16]]]


In [36]:
print(e.shape)

(6, 6, 6)


In [37]:
print(e.ndim)

3


In [38]:
print(e.size)

216


In [39]:
print(c.dtype)

int64


Mathematical operations on a np array


In [41]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [44]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

[[1 1 6]
 [8 9 6]
 [5 8 8]]
[[15 12 18]
 [16 16 18]
 [14 10 13]]


In [46]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[16 13 24]
 [24 25 24]
 [19 18 21]]
[[-14 -11 -12]
 [ -8  -7 -12]
 [ -9  -2  -5]]
[[ 15  12 108]
 [128 144 108]
 [ 70  80 104]]
[[0.06666667 0.08333333 0.33333333]
 [0.5        0.5625     0.33333333]
 [0.35714286 0.8        0.61538462]]


In [48]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[16 13 24]
 [24 25 24]
 [19 18 21]]
[[-14 -11 -12]
 [ -8  -7 -12]
 [ -9  -2  -5]]
[[ 15  12 108]
 [128 144 108]
 [ 70  80 104]]
[[0.06666667 0.08333333 0.33333333]
 [0.5        0.5625     0.33333333]
 [0.35714286 0.8        0.61538462]]


Array Manipulation

In [51]:
array=np.random.randint(0,10,(4,5))
print(array)
print(array.shape)

[[8 3 0 7 3]
 [0 6 9 0 2]
 [5 9 0 4 8]
 [8 5 0 8 4]]
(4, 5)


In [53]:
#transpose
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[8 0 5 8]
 [3 6 9 5]
 [0 9 0 0]
 [7 0 4 8]
 [3 2 8 4]]
(5, 4)


In [54]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 7 6]
 [0 8 3]]
(2, 3)


In [56]:
trans2=array.T
print(trans2)
print(trans2.shape)

[[9 0]
 [7 8]
 [6 3]]
(3, 2)


ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [59]:
#reshaping a array
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[7 6 0]
 [0 0 3]]
(2, 3)


In [60]:
b= a.reshape(3,2)
print(b)
print(b.shape)

[[7 6]
 [0 0]
 [0 3]]
(3, 2)
